CREATE TABLE membership_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id VARCHAR(100) UNIQUE,
    plan_name VARCHAR(300) NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    duration BIGINT NOT NULL,
    description VARCHAR(500),
    is_active SMALLINT NOT NULL DEFAULT 1,
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_at TIMESTAMP,
    CONSTRAINT chk_membership_plans_is_active CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_membership_plans_is_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_membership_plans_created_by
        FOREIGN KEY (created_by)
        REFERENCES app_users (id),
    CONSTRAINT fk_membership_plans_update_by
        FOREIGN KEY (update_by)
        REFERENCES app_users (id)
);

CREATE UNIQUE INDEX uq_membership_plans_plan_name_lower
    ON membership_plans (LOWER(plan_name));

CREATE INDEX idx_membership_plans_created_by
    ON membership_plans (created_by);

CREATE INDEX idx_membership_plans_update_by
    ON membership_plans (update_by);
