CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_users_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    role_id BIGINT NOT NULL,
    CONSTRAINT uq_app_users_roles_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_app_users_roles_user
        FOREIGN KEY (user_id)
        REFERENCES app_users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_app_users_roles_role
        FOREIGN KEY (role_id)
        REFERENCES app_roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_app_users_email ON app_users (email);
CREATE INDEX idx_app_users_status ON app_users (status);
CREATE INDEX idx_app_roles_name ON app_roles (name);
CREATE INDEX idx_app_users_roles_role_id ON app_users_roles (role_id);
