CREATE TABLE app_genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    created_date DATE NOT NULL,
    description VARCHAR(500),
    is_active SMALLINT NOT NULL DEFAULT 1,
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    create_by BIGINT NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_app_genre_is_active CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_app_genre_is_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_app_genre_create_by
        FOREIGN KEY (create_by)
        REFERENCES app_users (id)
);

CREATE INDEX idx_app_genre_name ON app_genre (name);
CREATE INDEX idx_app_genre_is_active ON app_genre (is_active);
CREATE INDEX idx_app_genre_is_deleted ON app_genre (is_deleted);
CREATE INDEX idx_app_genre_create_by ON app_genre (create_by);
