CREATE TABLE story_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_date DATE,
    is_active SMALLINT NOT NULL DEFAULT 1,
    description VARCHAR(500),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_story_type_is_active CHECK (is_active IN (0, 1)),
    CONSTRAINT chk_story_type_is_deleted CHECK (is_deleted IN (0, 1)),
    CONSTRAINT fk_story_type_created_by
        FOREIGN KEY (created_by)
        REFERENCES app_users (id)
);

CREATE INDEX idx_story_type_name ON story_type (name);
CREATE INDEX idx_story_type_created_date ON story_type (created_date);
CREATE INDEX idx_story_type_is_active ON story_type (is_active);
CREATE INDEX idx_story_type_is_deleted ON story_type (is_deleted);
CREATE INDEX idx_story_type_created_by ON story_type (created_by);
